# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "sergo03"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.5-2701ad5"
  arch: amd64

secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
