name: KBOT-CICD

on: push

jobs:
  ci: 
      name: CI
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
         
        - name: Run test
          run: make test  
        - name: Create a Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
        
          
      